### ISSUE TITLE
Display Stocks on Website 

### ISSUE THREAD

**Issue by timnUB** [UB-CSE/course-project-the-wolves-of-a9#13]
When I enter the page, there should be a table on the front.
The table should contain stocks, and info about those stocks.
The table should display an image in the right column which contains a graph.

**Comment by jason-kuang** [comment]
I think this also is more of a story rather than a task.

**Comment by timnUB** [comment]
When I enter the page, there should be a table on the front.
The table should contain stocks, and their prices
The table should display an image in the right column which contains a cell for a graph.
