### ISSUE TITLE
Link Email Alerts to Server

### ISSUE THREAD

**Issue by jason-kuang** [UB-CSE/course-project-the-wolves-of-a9#30]
Users should be getting emails about events that could have impacted the stock market.

Currently, we have the email system but users will not receive emails because it is not linked.
Upon completion, a user should be able to register and confirm they would like to receive daily emails.
Once a day, users should receive emails after the market closes.

**Comment by vasunep0306** [comment]
make sure you write your acceptance tests.

**Comment by ericsant** [comment]
All users opt in for daily emails receive an email each day before the market open

Users receive a confirmation email during signup
